#! /bin/sh

###########
# Autostart
###########

# Hotkeys
pgrep -x sxhkd > /dev/null || sxhkd &

# Polkit
pgrep polkit-gnome-authentication-agent-1 > /dev/null || /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Bar
~/.config/polybar/launch.sh &

# Notifications
pgrep -x dunst > /dev/null || dunst &

# Network Applet
pgrep -x nm-applet > /dev/null || nm-applet --indicator &

# Picom
pgrep -x picom > /dev/null || picom -CGb &

# Wallpaper
nitrogen --restore &

# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &

# Cursor
xsetroot -cursor_name left_ptr &

###########
# BSPWM
###########

# Set monitors
bspc monitor -d I II III IV V VI VII VIII IX X

# Basic configuration
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a msedge desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Border
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"