#!/usr/bin/env bash

###########
# Autostart
###########

# Hotkeys
pgrep -x sxhkd > /dev/null || sxhkd &

# Polkit
pgrep polkit-gnome-authentication-agent-1 > /dev/null || /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Bar
~/.config/polybar/launch.sh &

# Notifications
pgrep -x dunst > /dev/null || dunst &

# Network Applet
pgrep -x nm-applet > /dev/null || nm-applet --indicator &

# Picom
# pgrep -x picom > /dev/null || picom -CGb &

# Wallpaper
nitrogen --restore &

# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &

# Load Nvidia settings
nvidia-settings --load-config-only

# Cursor
xsetroot -cursor_name left_ptr &

# Fix java window reparenting issue (e.g clion, intellij)
wmname LG3D

# SSH Agent
ssh-agent startx

###########
# BSPWM
###########

# Ensure all rules are deleted
bspc rule -r "*"

# Set monitors
bspc monitor DP-2 -f -d I II III IV V
bspc monitor DP-4 -d VI VII VIII IX X

# Basic configuration
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

# Border
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

# Rules
#bspc rule -a firefox desktop='Browser' follow=on focus=on
#bspc rule -a Microsoft-edge desktop='Browser' follow=on focus=on
bspc rule -a Eddie desktop='IV' state=floating follow=on
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Send notification
notify-send 'BSPWM re/started!' &
